name: Unit test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "macos-12", "windows-2022"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    env:
      COVERAGE_FILE: .coverage_${{ matrix.os }}_${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install library
        run: poetry install --no-interaction

      - name: Run test and generate coverage report
        run: poetry run pytest --verbose --cov=classopt --cov-report=term-missing:skip-covered --cov-config=pyproject.toml

      - name: Archive coverage results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.COVERAGE_FILE }}
          path: ${{ env.COVERAGE_FILE }}

  report:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Download all workflow artifacts
        uses: actions/download-artifact@v3
        with:
          path: reports

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Set up coverage
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage

      - name: Combine reports
        run: coverage combine --keep ./reports/.coverage*/.coverage*

      - name: Report
        run: coverage report --skip-covered --show-missing --skip-empty | tee coverage.txt

      - name: XML
        run: coverage xml

      - name: Archive coverage results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: |
            .coverage
            coverage.txt
            coverage.xml

      - name: Python Coverage
        uses: orgoro/coverage@v2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
